// Code generated by generate-abi-bindings.js — DO NOT EDIT.
package abi

import (
	"encoding/json"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

// ITreasuryABIJson is the raw ABI JSON for ITreasury.
const ITreasuryABIJson = `[{"inputs":[],"name":"InsufficientBalance","type":"error"},{"inputs":[],"name":"Unauthorized","type":"error"},{"inputs":[],"name":"ZeroAddress","type":"error"},{"inputs":[],"name":"ZeroAmount","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"token","type":"address"},{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Deposited","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"token","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Withdrawn","type":"event"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"deposit","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"getBalance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}]`

// ITreasuryABI returns the parsed go-ethereum ABI for ITreasury.
func ITreasuryABI() (abi.ABI, error) {
	return abi.JSON(strings.NewReader(ITreasuryABIJson))
}

// MustITreasuryABI is like ITreasuryABI but panics on error.
func MustITreasuryABI() abi.ABI {
	parsed, err := ITreasuryABI()
	if err != nil {
		panic("failed to parse ITreasury ABI: " + err.Error())
	}
	return parsed
}

// ITreasuryABIParsed returns the ABI as []map[string]interface{}.
func ITreasuryABIParsed() ([]map[string]interface{}, error) {
	var out []map[string]interface{}
	err := json.Unmarshal([]byte(ITreasuryABIJson), &out)
	return out, err
}

// --- Function names ---
const (
	ITreasuryFnDeposit = "deposit"
	ITreasuryFnGetBalance = "getBalance"
	ITreasuryFnWithdraw = "withdraw"
)

// --- Event names ---
const (
	ITreasuryEvtDeposited = "Deposited"
	ITreasuryEvtWithdrawn = "Withdrawn"
)
