// Code generated by generate-abi-bindings.js — DO NOT EDIT.
package abi

import (
	"encoding/json"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

// ISidioraNFTABIJson is the raw ABI JSON for ISidioraNFT.
const ISidioraNFTABIJson = `[{"inputs":[],"name":"InvalidStrategy","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":false,"internalType":"uint8","name":"oldStrategy","type":"uint8"},{"indexed":false,"internalType":"uint8","name":"newStrategy","type":"uint8"}],"name":"FeeStrategyChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"creator","type":"address"},{"indexed":true,"internalType":"address","name":"pool","type":"address"}],"name":"PoolNFTMinted","type":"event"},{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"getFeeStrategy","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"getPoolAddress","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"address","name":"pool","type":"address"},{"internalType":"uint8","name":"strategy","type":"uint8"}],"name":"mint","outputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"nextTokenId","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"uint8","name":"newStrategy","type":"uint8"}],"name":"setFeeStrategy","outputs":[],"stateMutability":"nonpayable","type":"function"}]`

// ISidioraNFTABI returns the parsed go-ethereum ABI for ISidioraNFT.
func ISidioraNFTABI() (abi.ABI, error) {
	return abi.JSON(strings.NewReader(ISidioraNFTABIJson))
}

// MustISidioraNFTABI is like ISidioraNFTABI but panics on error.
func MustISidioraNFTABI() abi.ABI {
	parsed, err := ISidioraNFTABI()
	if err != nil {
		panic("failed to parse ISidioraNFT ABI: " + err.Error())
	}
	return parsed
}

// ISidioraNFTABIParsed returns the ABI as []map[string]interface{}.
func ISidioraNFTABIParsed() ([]map[string]interface{}, error) {
	var out []map[string]interface{}
	err := json.Unmarshal([]byte(ISidioraNFTABIJson), &out)
	return out, err
}

// --- Function names ---
const (
	ISidioraNFTFnGetFeeStrategy = "getFeeStrategy"
	ISidioraNFTFnGetPoolAddress = "getPoolAddress"
	ISidioraNFTFnMint = "mint"
	ISidioraNFTFnNextTokenId = "nextTokenId"
	ISidioraNFTFnSetFeeStrategy = "setFeeStrategy"
)

// --- Event names ---
const (
	ISidioraNFTEvtFeeStrategyChanged = "FeeStrategyChanged"
	ISidioraNFTEvtPoolNFTMinted = "PoolNFTMinted"
)
