// Code generated by generate-abi-bindings.js — DO NOT EDIT.
package abi

import (
	"encoding/json"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

// PoolBeaconABIJson is the raw ABI JSON for PoolBeacon.
const PoolBeaconABIJson = `[{"inputs":[{"internalType":"address","name":"initialImplementation","type":"address"},{"internalType":"address","name":"initialOwner","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"InvalidImplementation","type":"error"},{"inputs":[],"name":"Unauthorized","type":"error"},{"inputs":[],"name":"ZeroAddress","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"inputs":[],"name":"implementation","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"}],"name":"upgradeTo","outputs":[],"stateMutability":"nonpayable","type":"function"}]`

// PoolBeaconABI returns the parsed go-ethereum ABI for PoolBeacon.
func PoolBeaconABI() (abi.ABI, error) {
	return abi.JSON(strings.NewReader(PoolBeaconABIJson))
}

// MustPoolBeaconABI is like PoolBeaconABI but panics on error.
func MustPoolBeaconABI() abi.ABI {
	parsed, err := PoolBeaconABI()
	if err != nil {
		panic("failed to parse PoolBeacon ABI: " + err.Error())
	}
	return parsed
}

// PoolBeaconABIParsed returns the ABI as []map[string]interface{}.
func PoolBeaconABIParsed() ([]map[string]interface{}, error) {
	var out []map[string]interface{}
	err := json.Unmarshal([]byte(PoolBeaconABIJson), &out)
	return out, err
}

// --- Function names ---
const (
	PoolBeaconFnImplementation = "implementation"
	PoolBeaconFnOwner = "owner"
	PoolBeaconFnTransferOwnership = "transferOwnership"
	PoolBeaconFnUpgradeTo = "upgradeTo"
)

// --- Event names ---
const (
	PoolBeaconEvtOwnershipTransferred = "OwnershipTransferred"
	PoolBeaconEvtUpgraded = "Upgraded"
)
