// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	CompleteBackfillJob(ctx context.Context, id string) error
	FailBackfillJob(ctx context.Context, arg FailBackfillJobParams) error
	GetActiveBackfillJob(ctx context.Context) (IndexerBackfillJob, error)
	GetCursor(ctx context.Context, chainID int32) (IndexerCursor, error)
	GetPoolByPoolID(ctx context.Context, poolID string) (IndexerPool, error)
	GetPoolCount(ctx context.Context) (int64, error)
	GetSwapCount(ctx context.Context) (int64, error)
	InsertBackfillJob(ctx context.Context, arg InsertBackfillJobParams) error
	InsertConfigUpdate(ctx context.Context, arg InsertConfigUpdateParams) error
	InsertFeeDistribution(ctx context.Context, arg InsertFeeDistributionParams) error
	InsertFeeEvent(ctx context.Context, arg InsertFeeEventParams) error
	InsertFeeStrategyChange(ctx context.Context, arg InsertFeeStrategyChangeParams) error
	InsertOpticalExecution(ctx context.Context, arg InsertOpticalExecutionParams) error
	InsertPool(ctx context.Context, arg InsertPoolParams) error
	InsertPoolStateSnapshot(ctx context.Context, arg InsertPoolStateSnapshotParams) error
	InsertSwap(ctx context.Context, arg InsertSwapParams) error
	InsertTokenForTokenSwap(ctx context.Context, arg InsertTokenForTokenSwapParams) error
	UpdateBackfillProgress(ctx context.Context, arg UpdateBackfillProgressParams) error
	UpsertCursor(ctx context.Context, arg UpsertCursorParams) error
}

var _ Querier = (*Queries)(nil)
